services:
  db:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    restart: on-failure
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ADVERTISED_HOSTNAME=store-db
      - ALLOW_EMPTY_PASSWORD=yes
